version: "3.1"
services:

  database:
    image: postgres:11-alpine
    container_name: todo-spring-app-postgres
    volumes:
      - ./:/app
      - ./postgres-dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  webserver:
    image: nginx:alpine
    container_name: todo-spring-app-webserver
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    env_file:
      - ./.env

  app:
    build: docker/app
    container_name: todo-spring-app
    working_dir: /app
    env_file:
      - .env
    tty: true
    volumes:
      - ./:/app
    ports:
      - "5009:5009"

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: todo-spring-app-rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq:cached
    ports:
      - 15672:15672

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: todo-spring-app-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  rabbitmq: